import type { Config } from 'tailwindcss';

export default {
  content: [
    './app/components/**/*.{js,vue,ts}',
    './app/layouts/**/*.vue',
    './app/pages/**/*.vue',
    './content/**/*.md',
    './packages/object-transformer/src/**/*.{js,vue,ts}',
    './packages/object-transformer/src/components/**/*-variants.ts',
  ],
  safelist: [
    // Force include all common utility classes
    { pattern: /^(flex|grid|block|inline|hidden)$/ },
    { pattern: /^(relative|absolute|fixed|sticky)$/ },
    { pattern: /^gap-/ },
    { pattern: /^p-/ },
    { pattern: /^m-/ },
    { pattern: /^w-/ },
    { pattern: /^h-/ },
    { pattern: /^text-/ },
    { pattern: /^bg-/ },
    { pattern: /^border-/ },
    { pattern: /^rounded-/ },
    { pattern: /^opacity-/ },
    { pattern: /^z-/ },
    { pattern: /^overflow-/ },
    { pattern: /^transition-/ },
    { pattern: /^duration-/ },
    { pattern: /^cursor-/ },
    { pattern: /^(group|hover|focus):/ },
    { pattern: /^md:/ },
    { pattern: /^max-md:/ },
    { pattern: /^group-hover:/ },
    // Specific important classes
    'group',
    'flex-1',
    'flex-col',
    'items-center',
    'justify-between',
    'min-h-0',
    'min-w-fit',
    'shrink-0',
    'whitespace-pre-wrap',
    'italic',
    // ObjectNode specific classes
    'text-xs',
    'object-node-root',
    'my-1',
    'ml-2',
    '-ml-0.5',
    'pl-1.5',
    'gap-2',
    'hover:bg-accent/30',
    'group-hover:border-l-2',
    'group-hover:border-primary',
    'group-hover:pl-2.5',
    'text-muted-foreground',
    'md:ml-auto',
  ],
} as Config;
